# Generated by Django 3.2.9 on 2021-11-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
